// Mocks generated by Mockito 5.4.5 from annotations
// in platform_common/test/helper/mock_provider_helper.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i17;

import 'package:drift/drift.dart' as _i7;
import 'package:drift/src/runtime/executor/stream_queries.dart' as _i16;
import 'package:firebase_core/firebase_core.dart' as _i2;
import 'package:firebase_messaging/firebase_messaging.dart' as _i21;
import 'package:firebase_messaging_platform_interface/firebase_messaging_platform_interface.dart'
    as _i3;
import 'package:firebase_remote_config/firebase_remote_config.dart' as _i4;
import 'package:flutter/foundation.dart' as _i23;
import 'package:flutter_secure_storage/flutter_secure_storage.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i19;
import 'package:platform_common/config.dart' as _i22;
import 'package:platform_common/src/application/sync/job_manager.dart' as _i24;
import 'package:platform_common/src/data/core/config_repository.dart' as _i18;
import 'package:platform_common/src/data/core/log_services.dart' as _i25;
import 'package:platform_common/src/data/database/auth_token_dao.dart' as _i10;
import 'package:platform_common/src/data/database/core/app_database.dart'
    as _i8;
import 'package:platform_common/src/data/database/job_dao.dart' as _i12;
import 'package:platform_common/src/data/database/movie_description/movie_description_dao.dart'
    as _i15;
import 'package:platform_common/src/data/database/movie_list/movie_list_dao.dart'
    as _i14;
import 'package:platform_common/src/data/database/notification_dao.dart'
    as _i11;
import 'package:platform_common/src/data/database/user_dao.dart' as _i9;
import 'package:platform_common/src/data/database/user_list/user_list_dao.dart'
    as _i13;
import 'package:platform_common/src/utils/error_logger.dart' as _i20;
import 'package:rxdart/rxdart.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFirebaseApp_0 extends _i1.SmartFake implements _i2.FirebaseApp {
  _FakeFirebaseApp_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNotificationSettings_1 extends _i1.SmartFake
    implements _i3.NotificationSettings {
  _FakeNotificationSettings_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDateTime_2 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRemoteConfigSettings_3 extends _i1.SmartFake
    implements _i4.RemoteConfigSettings {
  _FakeRemoteConfigSettings_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRemoteConfigValue_4 extends _i1.SmartFake
    implements _i4.RemoteConfigValue {
  _FakeRemoteConfigValue_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIOSOptions_5 extends _i1.SmartFake implements _i5.IOSOptions {
  _FakeIOSOptions_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAndroidOptions_6 extends _i1.SmartFake
    implements _i5.AndroidOptions {
  _FakeAndroidOptions_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLinuxOptions_7 extends _i1.SmartFake implements _i5.LinuxOptions {
  _FakeLinuxOptions_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWindowsOptions_8 extends _i1.SmartFake
    implements _i5.WindowsOptions {
  _FakeWindowsOptions_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWebOptions_9 extends _i1.SmartFake implements _i5.WebOptions {
  _FakeWebOptions_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMacOsOptions_10 extends _i1.SmartFake implements _i5.MacOsOptions {
  _FakeMacOsOptions_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBehaviorSubject_11<T> extends _i1.SmartFake
    implements _i6.BehaviorSubject<T> {
  _FakeBehaviorSubject_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMigrationStrategy_12 extends _i1.SmartFake
    implements _i7.MigrationStrategy {
  _FakeMigrationStrategy_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$UsersTable_13 extends _i1.SmartFake implements _i8.$UsersTable {
  _Fake$UsersTable_13(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$AuthTokensTable_14 extends _i1.SmartFake
    implements _i8.$AuthTokensTable {
  _Fake$AuthTokensTable_14(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$NotificationsTable_15 extends _i1.SmartFake
    implements _i8.$NotificationsTable {
  _Fake$NotificationsTable_15(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$JobsTable_16 extends _i1.SmartFake implements _i8.$JobsTable {
  _Fake$JobsTable_16(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$UserListsTable_17 extends _i1.SmartFake
    implements _i8.$UserListsTable {
  _Fake$UserListsTable_17(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$MovieListsTable_18 extends _i1.SmartFake
    implements _i8.$MovieListsTable {
  _Fake$MovieListsTable_18(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$MovieDescriptionsTable_19 extends _i1.SmartFake
    implements _i8.$MovieDescriptionsTable {
  _Fake$MovieDescriptionsTable_19(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserDao_20 extends _i1.SmartFake implements _i9.UserDao {
  _FakeUserDao_20(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthTokenDao_21 extends _i1.SmartFake implements _i10.AuthTokenDao {
  _FakeAuthTokenDao_21(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNotificationDao_22 extends _i1.SmartFake
    implements _i11.NotificationDao {
  _FakeNotificationDao_22(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeJobDao_23 extends _i1.SmartFake implements _i12.JobDao {
  _FakeJobDao_23(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUserListDao_24 extends _i1.SmartFake implements _i13.UserListDao {
  _FakeUserListDao_24(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMovieListDao_25 extends _i1.SmartFake implements _i14.MovieListDao {
  _FakeMovieListDao_25(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMovieDescriptionDao_26 extends _i1.SmartFake
    implements _i15.MovieDescriptionDao {
  _FakeMovieDescriptionDao_26(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _Fake$AppDatabaseManager_27 extends _i1.SmartFake
    implements _i8.$AppDatabaseManager {
  _Fake$AppDatabaseManager_27(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGeneratedDatabase_28 extends _i1.SmartFake
    implements _i7.GeneratedDatabase {
  _FakeGeneratedDatabase_28(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDriftDatabaseOptions_29 extends _i1.SmartFake
    implements _i7.DriftDatabaseOptions {
  _FakeDriftDatabaseOptions_29(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStreamQueryUpdateRules_30 extends _i1.SmartFake
    implements _i7.StreamQueryUpdateRules {
  _FakeStreamQueryUpdateRules_30(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDatabaseConnection_31 extends _i1.SmartFake
    implements _i7.DatabaseConnection {
  _FakeDatabaseConnection_31(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeQueryExecutor_32 extends _i1.SmartFake implements _i7.QueryExecutor {
  _FakeQueryExecutor_32(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeStreamQueryStore_33 extends _i1.SmartFake
    implements _i16.StreamQueryStore {
  _FakeStreamQueryStore_33(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDatabaseConnectionUser_34 extends _i1.SmartFake
    implements _i7.DatabaseConnectionUser {
  _FakeDatabaseConnectionUser_34(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeMigrator_35 extends _i1.SmartFake implements _i7.Migrator {
  _FakeMigrator_35(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFuture_36<T1> extends _i1.SmartFake implements _i17.Future<T1> {
  _FakeFuture_36(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeInsertStatement_37<T1 extends _i7.Table, D1> extends _i1.SmartFake
    implements _i7.InsertStatement<T1, D1> {
  _FakeInsertStatement_37(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUpdateStatement_38<T extends _i7.Table, D> extends _i1.SmartFake
    implements _i7.UpdateStatement<T, D> {
  _FakeUpdateStatement_38(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSimpleSelectStatement_39<T1 extends _i7.HasResultSet, D>
    extends _i1.SmartFake
    implements _i7.SimpleSelectStatement<T1, D> {
  _FakeSimpleSelectStatement_39(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeJoinedSelectStatement_40<FirstT extends _i7.HasResultSet, FirstD>
    extends _i1.SmartFake
    implements _i7.JoinedSelectStatement<FirstT, FirstD> {
  _FakeJoinedSelectStatement_40(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBaseSelectStatement_41<Row> extends _i1.SmartFake
    implements _i7.BaseSelectStatement<Row> {
  _FakeBaseSelectStatement_41(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDeleteStatement_42<T1 extends _i7.Table, D1> extends _i1.SmartFake
    implements _i7.DeleteStatement<T1, D1> {
  _FakeDeleteStatement_42(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSelectable_43<T> extends _i1.SmartFake implements _i7.Selectable<T> {
  _FakeSelectable_43(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeGenerationContext_44 extends _i1.SmartFake
    implements _i7.GenerationContext {
  _FakeGenerationContext_44(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ConfigRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockConfigRepository extends _i1.Mock implements _i18.ConfigRepository {
  MockConfigRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get restBaseUrlDev =>
      (super.noSuchMethod(
            Invocation.getter(#restBaseUrlDev),
            returnValue: _i19.dummyValue<String>(
              this,
              Invocation.getter(#restBaseUrlDev),
            ),
          )
          as String);

  @override
  String get identityServerUrlDev =>
      (super.noSuchMethod(
            Invocation.getter(#identityServerUrlDev),
            returnValue: _i19.dummyValue<String>(
              this,
              Invocation.getter(#identityServerUrlDev),
            ),
          )
          as String);

  @override
  String get authRedirectUriDev =>
      (super.noSuchMethod(
            Invocation.getter(#authRedirectUriDev),
            returnValue: _i19.dummyValue<String>(
              this,
              Invocation.getter(#authRedirectUriDev),
            ),
          )
          as String);

  @override
  String get logoutRedirectUriDev =>
      (super.noSuchMethod(
            Invocation.getter(#logoutRedirectUriDev),
            returnValue: _i19.dummyValue<String>(
              this,
              Invocation.getter(#logoutRedirectUriDev),
            ),
          )
          as String);

  @override
  String get restBaseUrlQA =>
      (super.noSuchMethod(
            Invocation.getter(#restBaseUrlQA),
            returnValue: _i19.dummyValue<String>(
              this,
              Invocation.getter(#restBaseUrlQA),
            ),
          )
          as String);

  @override
  String get authRedirectUriQA =>
      (super.noSuchMethod(
            Invocation.getter(#authRedirectUriQA),
            returnValue: _i19.dummyValue<String>(
              this,
              Invocation.getter(#authRedirectUriQA),
            ),
          )
          as String);

  @override
  String get identityServerUrlQA =>
      (super.noSuchMethod(
            Invocation.getter(#identityServerUrlQA),
            returnValue: _i19.dummyValue<String>(
              this,
              Invocation.getter(#identityServerUrlQA),
            ),
          )
          as String);

  @override
  String get restBaseUrlStaging =>
      (super.noSuchMethod(
            Invocation.getter(#restBaseUrlStaging),
            returnValue: _i19.dummyValue<String>(
              this,
              Invocation.getter(#restBaseUrlStaging),
            ),
          )
          as String);

  @override
  String get authRedirectUriStaging =>
      (super.noSuchMethod(
            Invocation.getter(#authRedirectUriStaging),
            returnValue: _i19.dummyValue<String>(
              this,
              Invocation.getter(#authRedirectUriStaging),
            ),
          )
          as String);

  @override
  String get identityServerUrlStaging =>
      (super.noSuchMethod(
            Invocation.getter(#identityServerUrlStaging),
            returnValue: _i19.dummyValue<String>(
              this,
              Invocation.getter(#identityServerUrlStaging),
            ),
          )
          as String);

  @override
  String get restBaseUrlProd =>
      (super.noSuchMethod(
            Invocation.getter(#restBaseUrlProd),
            returnValue: _i19.dummyValue<String>(
              this,
              Invocation.getter(#restBaseUrlProd),
            ),
          )
          as String);

  @override
  String get identityServerUrlProd =>
      (super.noSuchMethod(
            Invocation.getter(#identityServerUrlProd),
            returnValue: _i19.dummyValue<String>(
              this,
              Invocation.getter(#identityServerUrlProd),
            ),
          )
          as String);

  @override
  String get authRedirectUriProd =>
      (super.noSuchMethod(
            Invocation.getter(#authRedirectUriProd),
            returnValue: _i19.dummyValue<String>(
              this,
              Invocation.getter(#authRedirectUriProd),
            ),
          )
          as String);

  @override
  String get logoutRedirectUriProd =>
      (super.noSuchMethod(
            Invocation.getter(#logoutRedirectUriProd),
            returnValue: _i19.dummyValue<String>(
              this,
              Invocation.getter(#logoutRedirectUriProd),
            ),
          )
          as String);

  @override
  String get tenantIDDev =>
      (super.noSuchMethod(
            Invocation.getter(#tenantIDDev),
            returnValue: _i19.dummyValue<String>(
              this,
              Invocation.getter(#tenantIDDev),
            ),
          )
          as String);

  @override
  String get clientIDDev =>
      (super.noSuchMethod(
            Invocation.getter(#clientIDDev),
            returnValue: _i19.dummyValue<String>(
              this,
              Invocation.getter(#clientIDDev),
            ),
          )
          as String);

  @override
  String get clientSecretDev =>
      (super.noSuchMethod(
            Invocation.getter(#clientSecretDev),
            returnValue: _i19.dummyValue<String>(
              this,
              Invocation.getter(#clientSecretDev),
            ),
          )
          as String);

  @override
  String get tenantIDQA =>
      (super.noSuchMethod(
            Invocation.getter(#tenantIDQA),
            returnValue: _i19.dummyValue<String>(
              this,
              Invocation.getter(#tenantIDQA),
            ),
          )
          as String);

  @override
  String get clientIDQA =>
      (super.noSuchMethod(
            Invocation.getter(#clientIDQA),
            returnValue: _i19.dummyValue<String>(
              this,
              Invocation.getter(#clientIDQA),
            ),
          )
          as String);

  @override
  String get clientSecretQA =>
      (super.noSuchMethod(
            Invocation.getter(#clientSecretQA),
            returnValue: _i19.dummyValue<String>(
              this,
              Invocation.getter(#clientSecretQA),
            ),
          )
          as String);

  @override
  String get tenantIDStaging =>
      (super.noSuchMethod(
            Invocation.getter(#tenantIDStaging),
            returnValue: _i19.dummyValue<String>(
              this,
              Invocation.getter(#tenantIDStaging),
            ),
          )
          as String);

  @override
  String get clientIDStaging =>
      (super.noSuchMethod(
            Invocation.getter(#clientIDStaging),
            returnValue: _i19.dummyValue<String>(
              this,
              Invocation.getter(#clientIDStaging),
            ),
          )
          as String);

  @override
  String get clientSecretStaging =>
      (super.noSuchMethod(
            Invocation.getter(#clientSecretStaging),
            returnValue: _i19.dummyValue<String>(
              this,
              Invocation.getter(#clientSecretStaging),
            ),
          )
          as String);

  @override
  String get tenantIDProd =>
      (super.noSuchMethod(
            Invocation.getter(#tenantIDProd),
            returnValue: _i19.dummyValue<String>(
              this,
              Invocation.getter(#tenantIDProd),
            ),
          )
          as String);

  @override
  String get clientIDProd =>
      (super.noSuchMethod(
            Invocation.getter(#clientIDProd),
            returnValue: _i19.dummyValue<String>(
              this,
              Invocation.getter(#clientIDProd),
            ),
          )
          as String);

  @override
  String get clientSecretProd =>
      (super.noSuchMethod(
            Invocation.getter(#clientSecretProd),
            returnValue: _i19.dummyValue<String>(
              this,
              Invocation.getter(#clientSecretProd),
            ),
          )
          as String);

  @override
  String get restHeadsUrl =>
      (super.noSuchMethod(
            Invocation.getter(#restHeadsUrl),
            returnValue: _i19.dummyValue<String>(
              this,
              Invocation.getter(#restHeadsUrl),
            ),
          )
          as String);

  @override
  String get restEmployeeBasicDetailsUrl =>
      (super.noSuchMethod(
            Invocation.getter(#restEmployeeBasicDetailsUrl),
            returnValue: _i19.dummyValue<String>(
              this,
              Invocation.getter(#restEmployeeBasicDetailsUrl),
            ),
          )
          as String);

  @override
  String get restLeaveEntitlementUrl =>
      (super.noSuchMethod(
            Invocation.getter(#restLeaveEntitlementUrl),
            returnValue: _i19.dummyValue<String>(
              this,
              Invocation.getter(#restLeaveEntitlementUrl),
            ),
          )
          as String);

  @override
  String get restLeaveRequestListUrl =>
      (super.noSuchMethod(
            Invocation.getter(#restLeaveRequestListUrl),
            returnValue: _i19.dummyValue<String>(
              this,
              Invocation.getter(#restLeaveRequestListUrl),
            ),
          )
          as String);

  @override
  int get iOSMinVersionCodeDev =>
      (super.noSuchMethod(
            Invocation.getter(#iOSMinVersionCodeDev),
            returnValue: 0,
          )
          as int);

  @override
  int get iOSMinVersionCodeQA =>
      (super.noSuchMethod(
            Invocation.getter(#iOSMinVersionCodeQA),
            returnValue: 0,
          )
          as int);

  @override
  int get iOSMinVersionCodeStaging =>
      (super.noSuchMethod(
            Invocation.getter(#iOSMinVersionCodeStaging),
            returnValue: 0,
          )
          as int);

  @override
  int get iOSMinVersionCodeProd =>
      (super.noSuchMethod(
            Invocation.getter(#iOSMinVersionCodeProd),
            returnValue: 0,
          )
          as int);

  @override
  int get iOSLatestVersionCodeDev =>
      (super.noSuchMethod(
            Invocation.getter(#iOSLatestVersionCodeDev),
            returnValue: 0,
          )
          as int);

  @override
  int get iOSLatestVersionCodeQA =>
      (super.noSuchMethod(
            Invocation.getter(#iOSLatestVersionCodeQA),
            returnValue: 0,
          )
          as int);

  @override
  int get iOSLatestVersionCodeStaging =>
      (super.noSuchMethod(
            Invocation.getter(#iOSLatestVersionCodeStaging),
            returnValue: 0,
          )
          as int);

  @override
  int get iOSLatestVersionCodeProd =>
      (super.noSuchMethod(
            Invocation.getter(#iOSLatestVersionCodeProd),
            returnValue: 0,
          )
          as int);

  @override
  int get androidMinVersionCodeDev =>
      (super.noSuchMethod(
            Invocation.getter(#androidMinVersionCodeDev),
            returnValue: 0,
          )
          as int);

  @override
  int get androidMinVersionCodeQA =>
      (super.noSuchMethod(
            Invocation.getter(#androidMinVersionCodeQA),
            returnValue: 0,
          )
          as int);

  @override
  int get androidMinVersionCodeStaging =>
      (super.noSuchMethod(
            Invocation.getter(#androidMinVersionCodeStaging),
            returnValue: 0,
          )
          as int);

  @override
  int get androidMinVersionCodeProd =>
      (super.noSuchMethod(
            Invocation.getter(#androidMinVersionCodeProd),
            returnValue: 0,
          )
          as int);

  @override
  int get androidLatestVersionCodeDev =>
      (super.noSuchMethod(
            Invocation.getter(#androidLatestVersionCodeDev),
            returnValue: 0,
          )
          as int);

  @override
  int get androidLatestVersionCodeQA =>
      (super.noSuchMethod(
            Invocation.getter(#androidLatestVersionCodeQA),
            returnValue: 0,
          )
          as int);

  @override
  int get androidLatestVersionCodeStaging =>
      (super.noSuchMethod(
            Invocation.getter(#androidLatestVersionCodeStaging),
            returnValue: 0,
          )
          as int);

  @override
  int get androidLatestVersionCodeProd =>
      (super.noSuchMethod(
            Invocation.getter(#androidLatestVersionCodeProd),
            returnValue: 0,
          )
          as int);

  @override
  String get immediateUpdateTitle =>
      (super.noSuchMethod(
            Invocation.getter(#immediateUpdateTitle),
            returnValue: _i19.dummyValue<String>(
              this,
              Invocation.getter(#immediateUpdateTitle),
            ),
          )
          as String);

  @override
  String get immediateUpdateMessage =>
      (super.noSuchMethod(
            Invocation.getter(#immediateUpdateMessage),
            returnValue: _i19.dummyValue<String>(
              this,
              Invocation.getter(#immediateUpdateMessage),
            ),
          )
          as String);

  @override
  String get flexibleUpdateTitle =>
      (super.noSuchMethod(
            Invocation.getter(#flexibleUpdateTitle),
            returnValue: _i19.dummyValue<String>(
              this,
              Invocation.getter(#flexibleUpdateTitle),
            ),
          )
          as String);

  @override
  String get flexibleUpdateMessage =>
      (super.noSuchMethod(
            Invocation.getter(#flexibleUpdateMessage),
            returnValue: _i19.dummyValue<String>(
              this,
              Invocation.getter(#flexibleUpdateMessage),
            ),
          )
          as String);

  @override
  String get googleAPIKeyAndroid =>
      (super.noSuchMethod(
            Invocation.getter(#googleAPIKeyAndroid),
            returnValue: _i19.dummyValue<String>(
              this,
              Invocation.getter(#googleAPIKeyAndroid),
            ),
          )
          as String);

  @override
  String get googleAPIKeyIOS =>
      (super.noSuchMethod(
            Invocation.getter(#googleAPIKeyIOS),
            returnValue: _i19.dummyValue<String>(
              this,
              Invocation.getter(#googleAPIKeyIOS),
            ),
          )
          as String);

  @override
  String get googleAPIKeyBrowser =>
      (super.noSuchMethod(
            Invocation.getter(#googleAPIKeyBrowser),
            returnValue: _i19.dummyValue<String>(
              this,
              Invocation.getter(#googleAPIKeyBrowser),
            ),
          )
          as String);

  @override
  String get restRemoteConfigUrl =>
      (super.noSuchMethod(
            Invocation.getter(#restRemoteConfigUrl),
            returnValue: _i19.dummyValue<String>(
              this,
              Invocation.getter(#restRemoteConfigUrl),
            ),
          )
          as String);

  @override
  String get restRemoteConfigProviderUrl =>
      (super.noSuchMethod(
            Invocation.getter(#restRemoteConfigProviderUrl),
            returnValue: _i19.dummyValue<String>(
              this,
              Invocation.getter(#restRemoteConfigProviderUrl),
            ),
          )
          as String);

  @override
  String get synergyProxy =>
      (super.noSuchMethod(
            Invocation.getter(#synergyProxy),
            returnValue: _i19.dummyValue<String>(
              this,
              Invocation.getter(#synergyProxy),
            ),
          )
          as String);

  @override
  void setFirebaseRemoteConfig(_i4.FirebaseRemoteConfig? config) =>
      super.noSuchMethod(
        Invocation.method(#setFirebaseRemoteConfig, [config]),
        returnValueForMissingStub: null,
      );

  @override
  _i17.Future<void> initConfig() =>
      (super.noSuchMethod(
            Invocation.method(#initConfig, []),
            returnValue: _i17.Future<void>.value(),
            returnValueForMissingStub: _i17.Future<void>.value(),
          )
          as _i17.Future<void>);

  @override
  _i17.Future<void> syncConfig() =>
      (super.noSuchMethod(
            Invocation.method(#syncConfig, []),
            returnValue: _i17.Future<void>.value(),
            returnValueForMissingStub: _i17.Future<void>.value(),
          )
          as _i17.Future<void>);

  @override
  bool isInitialFetchCompleted() =>
      (super.noSuchMethod(
            Invocation.method(#isInitialFetchCompleted, []),
            returnValue: false,
          )
          as bool);

  @override
  _i17.Future<void> updateDefaultConfig(Map<String, dynamic>? defaultConfig) =>
      (super.noSuchMethod(
            Invocation.method(#updateDefaultConfig, [defaultConfig]),
            returnValue: _i17.Future<void>.value(),
            returnValueForMissingStub: _i17.Future<void>.value(),
          )
          as _i17.Future<void>);
}

/// A class which mocks [ErrorLogger].
///
/// See the documentation for Mockito's code generation for more information.
class MockErrorLogger extends _i1.Mock implements _i20.ErrorLogger {
  MockErrorLogger() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void recordError({
    dynamic exception,
    StackTrace? stackTrace,
    bool? fatal = false,
  }) => super.noSuchMethod(
    Invocation.method(#recordError, [], {
      #exception: exception,
      #stackTrace: stackTrace,
      #fatal: fatal,
    }),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [FirebaseMessaging].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirebaseMessaging extends _i1.Mock implements _i21.FirebaseMessaging {
  MockFirebaseMessaging() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FirebaseApp get app =>
      (super.noSuchMethod(
            Invocation.getter(#app),
            returnValue: _FakeFirebaseApp_0(this, Invocation.getter(#app)),
          )
          as _i2.FirebaseApp);

  @override
  set app(_i2.FirebaseApp? _app) => super.noSuchMethod(
    Invocation.setter(#app, _app),
    returnValueForMissingStub: null,
  );

  @override
  bool get isAutoInitEnabled =>
      (super.noSuchMethod(
            Invocation.getter(#isAutoInitEnabled),
            returnValue: false,
          )
          as bool);

  @override
  _i17.Stream<String> get onTokenRefresh =>
      (super.noSuchMethod(
            Invocation.getter(#onTokenRefresh),
            returnValue: _i17.Stream<String>.empty(),
          )
          as _i17.Stream<String>);

  @override
  Map<dynamic, dynamic> get pluginConstants =>
      (super.noSuchMethod(
            Invocation.getter(#pluginConstants),
            returnValue: <dynamic, dynamic>{},
          )
          as Map<dynamic, dynamic>);

  @override
  _i17.Future<_i3.RemoteMessage?> getInitialMessage() =>
      (super.noSuchMethod(
            Invocation.method(#getInitialMessage, []),
            returnValue: _i17.Future<_i3.RemoteMessage?>.value(),
          )
          as _i17.Future<_i3.RemoteMessage?>);

  @override
  _i17.Future<void> deleteToken() =>
      (super.noSuchMethod(
            Invocation.method(#deleteToken, []),
            returnValue: _i17.Future<void>.value(),
            returnValueForMissingStub: _i17.Future<void>.value(),
          )
          as _i17.Future<void>);

  @override
  _i17.Future<String?> getAPNSToken() =>
      (super.noSuchMethod(
            Invocation.method(#getAPNSToken, []),
            returnValue: _i17.Future<String?>.value(),
          )
          as _i17.Future<String?>);

  @override
  _i17.Future<String?> getToken({String? vapidKey}) =>
      (super.noSuchMethod(
            Invocation.method(#getToken, [], {#vapidKey: vapidKey}),
            returnValue: _i17.Future<String?>.value(),
          )
          as _i17.Future<String?>);

  @override
  _i17.Future<bool> isSupported() =>
      (super.noSuchMethod(
            Invocation.method(#isSupported, []),
            returnValue: _i17.Future<bool>.value(false),
          )
          as _i17.Future<bool>);

  @override
  _i17.Future<_i3.NotificationSettings> getNotificationSettings() =>
      (super.noSuchMethod(
            Invocation.method(#getNotificationSettings, []),
            returnValue: _i17.Future<_i3.NotificationSettings>.value(
              _FakeNotificationSettings_1(
                this,
                Invocation.method(#getNotificationSettings, []),
              ),
            ),
          )
          as _i17.Future<_i3.NotificationSettings>);

  @override
  _i17.Future<_i3.NotificationSettings> requestPermission({
    bool? alert = true,
    bool? announcement = false,
    bool? badge = true,
    bool? carPlay = false,
    bool? criticalAlert = false,
    bool? provisional = false,
    bool? sound = true,
    bool? providesAppNotificationSettings = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#requestPermission, [], {
              #alert: alert,
              #announcement: announcement,
              #badge: badge,
              #carPlay: carPlay,
              #criticalAlert: criticalAlert,
              #provisional: provisional,
              #sound: sound,
              #providesAppNotificationSettings: providesAppNotificationSettings,
            }),
            returnValue: _i17.Future<_i3.NotificationSettings>.value(
              _FakeNotificationSettings_1(
                this,
                Invocation.method(#requestPermission, [], {
                  #alert: alert,
                  #announcement: announcement,
                  #badge: badge,
                  #carPlay: carPlay,
                  #criticalAlert: criticalAlert,
                  #provisional: provisional,
                  #sound: sound,
                  #providesAppNotificationSettings:
                      providesAppNotificationSettings,
                }),
              ),
            ),
          )
          as _i17.Future<_i3.NotificationSettings>);

  @override
  _i17.Future<void> sendMessage({
    String? to,
    Map<String, String>? data,
    String? collapseKey,
    String? messageId,
    String? messageType,
    int? ttl,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendMessage, [], {
              #to: to,
              #data: data,
              #collapseKey: collapseKey,
              #messageId: messageId,
              #messageType: messageType,
              #ttl: ttl,
            }),
            returnValue: _i17.Future<void>.value(),
            returnValueForMissingStub: _i17.Future<void>.value(),
          )
          as _i17.Future<void>);

  @override
  _i17.Future<void> setAutoInitEnabled(bool? enabled) =>
      (super.noSuchMethod(
            Invocation.method(#setAutoInitEnabled, [enabled]),
            returnValue: _i17.Future<void>.value(),
            returnValueForMissingStub: _i17.Future<void>.value(),
          )
          as _i17.Future<void>);

  @override
  _i17.Future<void> setDeliveryMetricsExportToBigQuery(bool? enabled) =>
      (super.noSuchMethod(
            Invocation.method(#setDeliveryMetricsExportToBigQuery, [enabled]),
            returnValue: _i17.Future<void>.value(),
            returnValueForMissingStub: _i17.Future<void>.value(),
          )
          as _i17.Future<void>);

  @override
  _i17.Future<void> setForegroundNotificationPresentationOptions({
    bool? alert = false,
    bool? badge = false,
    bool? sound = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #setForegroundNotificationPresentationOptions,
              [],
              {#alert: alert, #badge: badge, #sound: sound},
            ),
            returnValue: _i17.Future<void>.value(),
            returnValueForMissingStub: _i17.Future<void>.value(),
          )
          as _i17.Future<void>);

  @override
  _i17.Future<void> subscribeToTopic(String? topic) =>
      (super.noSuchMethod(
            Invocation.method(#subscribeToTopic, [topic]),
            returnValue: _i17.Future<void>.value(),
            returnValueForMissingStub: _i17.Future<void>.value(),
          )
          as _i17.Future<void>);

  @override
  _i17.Future<void> unsubscribeFromTopic(String? topic) =>
      (super.noSuchMethod(
            Invocation.method(#unsubscribeFromTopic, [topic]),
            returnValue: _i17.Future<void>.value(),
            returnValueForMissingStub: _i17.Future<void>.value(),
          )
          as _i17.Future<void>);
}

/// A class which mocks [FirebaseRemoteConfig].
///
/// See the documentation for Mockito's code generation for more information.
class MockFirebaseRemoteConfig extends _i1.Mock
    implements _i4.FirebaseRemoteConfig {
  MockFirebaseRemoteConfig() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FirebaseApp get app =>
      (super.noSuchMethod(
            Invocation.getter(#app),
            returnValue: _FakeFirebaseApp_0(this, Invocation.getter(#app)),
          )
          as _i2.FirebaseApp);

  @override
  DateTime get lastFetchTime =>
      (super.noSuchMethod(
            Invocation.getter(#lastFetchTime),
            returnValue: _FakeDateTime_2(
              this,
              Invocation.getter(#lastFetchTime),
            ),
          )
          as DateTime);

  @override
  _i4.RemoteConfigFetchStatus get lastFetchStatus =>
      (super.noSuchMethod(
            Invocation.getter(#lastFetchStatus),
            returnValue: _i4.RemoteConfigFetchStatus.noFetchYet,
          )
          as _i4.RemoteConfigFetchStatus);

  @override
  _i4.RemoteConfigSettings get settings =>
      (super.noSuchMethod(
            Invocation.getter(#settings),
            returnValue: _FakeRemoteConfigSettings_3(
              this,
              Invocation.getter(#settings),
            ),
          )
          as _i4.RemoteConfigSettings);

  @override
  _i17.Stream<_i4.RemoteConfigUpdate> get onConfigUpdated =>
      (super.noSuchMethod(
            Invocation.getter(#onConfigUpdated),
            returnValue: _i17.Stream<_i4.RemoteConfigUpdate>.empty(),
          )
          as _i17.Stream<_i4.RemoteConfigUpdate>);

  @override
  Map<dynamic, dynamic> get pluginConstants =>
      (super.noSuchMethod(
            Invocation.getter(#pluginConstants),
            returnValue: <dynamic, dynamic>{},
          )
          as Map<dynamic, dynamic>);

  @override
  _i17.Future<bool> activate() =>
      (super.noSuchMethod(
            Invocation.method(#activate, []),
            returnValue: _i17.Future<bool>.value(false),
          )
          as _i17.Future<bool>);

  @override
  _i17.Future<void> ensureInitialized() =>
      (super.noSuchMethod(
            Invocation.method(#ensureInitialized, []),
            returnValue: _i17.Future<void>.value(),
            returnValueForMissingStub: _i17.Future<void>.value(),
          )
          as _i17.Future<void>);

  @override
  _i17.Future<void> fetch() =>
      (super.noSuchMethod(
            Invocation.method(#fetch, []),
            returnValue: _i17.Future<void>.value(),
            returnValueForMissingStub: _i17.Future<void>.value(),
          )
          as _i17.Future<void>);

  @override
  _i17.Future<bool> fetchAndActivate() =>
      (super.noSuchMethod(
            Invocation.method(#fetchAndActivate, []),
            returnValue: _i17.Future<bool>.value(false),
          )
          as _i17.Future<bool>);

  @override
  Map<String, _i4.RemoteConfigValue> getAll() =>
      (super.noSuchMethod(
            Invocation.method(#getAll, []),
            returnValue: <String, _i4.RemoteConfigValue>{},
          )
          as Map<String, _i4.RemoteConfigValue>);

  @override
  bool getBool(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#getBool, [key]),
            returnValue: false,
          )
          as bool);

  @override
  int getInt(String? key) =>
      (super.noSuchMethod(Invocation.method(#getInt, [key]), returnValue: 0)
          as int);

  @override
  double getDouble(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#getDouble, [key]),
            returnValue: 0.0,
          )
          as double);

  @override
  String getString(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#getString, [key]),
            returnValue: _i19.dummyValue<String>(
              this,
              Invocation.method(#getString, [key]),
            ),
          )
          as String);

  @override
  _i4.RemoteConfigValue getValue(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#getValue, [key]),
            returnValue: _FakeRemoteConfigValue_4(
              this,
              Invocation.method(#getValue, [key]),
            ),
          )
          as _i4.RemoteConfigValue);

  @override
  _i17.Future<void> setConfigSettings(
    _i4.RemoteConfigSettings? remoteConfigSettings,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#setConfigSettings, [remoteConfigSettings]),
            returnValue: _i17.Future<void>.value(),
            returnValueForMissingStub: _i17.Future<void>.value(),
          )
          as _i17.Future<void>);

  @override
  _i17.Future<void> setDefaults(Map<String, dynamic>? defaultParameters) =>
      (super.noSuchMethod(
            Invocation.method(#setDefaults, [defaultParameters]),
            returnValue: _i17.Future<void>.value(),
            returnValueForMissingStub: _i17.Future<void>.value(),
          )
          as _i17.Future<void>);

  @override
  _i17.Future<void> setCustomSignals(Map<String, Object?>? customSignals) =>
      (super.noSuchMethod(
            Invocation.method(#setCustomSignals, [customSignals]),
            returnValue: _i17.Future<void>.value(),
            returnValueForMissingStub: _i17.Future<void>.value(),
          )
          as _i17.Future<void>);
}

/// A class which mocks [Flavor].
///
/// See the documentation for Mockito's code generation for more information.
class MockFlavor extends _i1.Mock implements _i22.Flavor {
  MockFlavor() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get name =>
      (super.noSuchMethod(
            Invocation.getter(#name),
            returnValue: _i19.dummyValue<String>(
              this,
              Invocation.getter(#name),
            ),
          )
          as String);

  @override
  int get iOSMinVersionCode =>
      (super.noSuchMethod(Invocation.getter(#iOSMinVersionCode), returnValue: 0)
          as int);

  @override
  int get iOSLatestVersionCode =>
      (super.noSuchMethod(
            Invocation.getter(#iOSLatestVersionCode),
            returnValue: 0,
          )
          as int);

  @override
  int get androidMinVersionCode =>
      (super.noSuchMethod(
            Invocation.getter(#androidMinVersionCode),
            returnValue: 0,
          )
          as int);

  @override
  int get androidLatestVersionCode =>
      (super.noSuchMethod(
            Invocation.getter(#androidLatestVersionCode),
            returnValue: 0,
          )
          as int);

  @override
  String get restApiVersion =>
      (super.noSuchMethod(
            Invocation.getter(#restApiVersion),
            returnValue: _i19.dummyValue<String>(
              this,
              Invocation.getter(#restApiVersion),
            ),
          )
          as String);

  @override
  String get restBaseUrl =>
      (super.noSuchMethod(
            Invocation.getter(#restBaseUrl),
            returnValue: _i19.dummyValue<String>(
              this,
              Invocation.getter(#restBaseUrl),
            ),
          )
          as String);

  @override
  String get identityServerBaseUrl =>
      (super.noSuchMethod(
            Invocation.getter(#identityServerBaseUrl),
            returnValue: _i19.dummyValue<String>(
              this,
              Invocation.getter(#identityServerBaseUrl),
            ),
          )
          as String);

  @override
  String get authRedirectUri =>
      (super.noSuchMethod(
            Invocation.getter(#authRedirectUri),
            returnValue: _i19.dummyValue<String>(
              this,
              Invocation.getter(#authRedirectUri),
            ),
          )
          as String);

  @override
  String get tenantID =>
      (super.noSuchMethod(
            Invocation.getter(#tenantID),
            returnValue: _i19.dummyValue<String>(
              this,
              Invocation.getter(#tenantID),
            ),
          )
          as String);

  @override
  String get clientID =>
      (super.noSuchMethod(
            Invocation.getter(#clientID),
            returnValue: _i19.dummyValue<String>(
              this,
              Invocation.getter(#clientID),
            ),
          )
          as String);

  @override
  String get clientSecret =>
      (super.noSuchMethod(
            Invocation.getter(#clientSecret),
            returnValue: _i19.dummyValue<String>(
              this,
              Invocation.getter(#clientSecret),
            ),
          )
          as String);
}

/// A class which mocks [FlutterSecureStorage].
///
/// See the documentation for Mockito's code generation for more information.
class MockFlutterSecureStorage extends _i1.Mock
    implements _i5.FlutterSecureStorage {
  MockFlutterSecureStorage() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.IOSOptions get iOptions =>
      (super.noSuchMethod(
            Invocation.getter(#iOptions),
            returnValue: _FakeIOSOptions_5(this, Invocation.getter(#iOptions)),
          )
          as _i5.IOSOptions);

  @override
  _i5.AndroidOptions get aOptions =>
      (super.noSuchMethod(
            Invocation.getter(#aOptions),
            returnValue: _FakeAndroidOptions_6(
              this,
              Invocation.getter(#aOptions),
            ),
          )
          as _i5.AndroidOptions);

  @override
  _i5.LinuxOptions get lOptions =>
      (super.noSuchMethod(
            Invocation.getter(#lOptions),
            returnValue: _FakeLinuxOptions_7(
              this,
              Invocation.getter(#lOptions),
            ),
          )
          as _i5.LinuxOptions);

  @override
  _i5.WindowsOptions get wOptions =>
      (super.noSuchMethod(
            Invocation.getter(#wOptions),
            returnValue: _FakeWindowsOptions_8(
              this,
              Invocation.getter(#wOptions),
            ),
          )
          as _i5.WindowsOptions);

  @override
  _i5.WebOptions get webOptions =>
      (super.noSuchMethod(
            Invocation.getter(#webOptions),
            returnValue: _FakeWebOptions_9(
              this,
              Invocation.getter(#webOptions),
            ),
          )
          as _i5.WebOptions);

  @override
  _i5.MacOsOptions get mOptions =>
      (super.noSuchMethod(
            Invocation.getter(#mOptions),
            returnValue: _FakeMacOsOptions_10(
              this,
              Invocation.getter(#mOptions),
            ),
          )
          as _i5.MacOsOptions);

  @override
  void registerListener({
    required String? key,
    required _i23.ValueChanged<String?>? listener,
  }) => super.noSuchMethod(
    Invocation.method(#registerListener, [], {#key: key, #listener: listener}),
    returnValueForMissingStub: null,
  );

  @override
  void unregisterListener({
    required String? key,
    required _i23.ValueChanged<String?>? listener,
  }) => super.noSuchMethod(
    Invocation.method(#unregisterListener, [], {
      #key: key,
      #listener: listener,
    }),
    returnValueForMissingStub: null,
  );

  @override
  void unregisterAllListenersForKey({required String? key}) =>
      super.noSuchMethod(
        Invocation.method(#unregisterAllListenersForKey, [], {#key: key}),
        returnValueForMissingStub: null,
      );

  @override
  void unregisterAllListeners() => super.noSuchMethod(
    Invocation.method(#unregisterAllListeners, []),
    returnValueForMissingStub: null,
  );

  @override
  _i17.Future<void> write({
    required String? key,
    required String? value,
    _i5.IOSOptions? iOptions,
    _i5.AndroidOptions? aOptions,
    _i5.LinuxOptions? lOptions,
    _i5.WebOptions? webOptions,
    _i5.MacOsOptions? mOptions,
    _i5.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#write, [], {
              #key: key,
              #value: value,
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i17.Future<void>.value(),
            returnValueForMissingStub: _i17.Future<void>.value(),
          )
          as _i17.Future<void>);

  @override
  _i17.Future<String?> read({
    required String? key,
    _i5.IOSOptions? iOptions,
    _i5.AndroidOptions? aOptions,
    _i5.LinuxOptions? lOptions,
    _i5.WebOptions? webOptions,
    _i5.MacOsOptions? mOptions,
    _i5.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#read, [], {
              #key: key,
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i17.Future<String?>.value(),
          )
          as _i17.Future<String?>);

  @override
  _i17.Future<bool> containsKey({
    required String? key,
    _i5.IOSOptions? iOptions,
    _i5.AndroidOptions? aOptions,
    _i5.LinuxOptions? lOptions,
    _i5.WebOptions? webOptions,
    _i5.MacOsOptions? mOptions,
    _i5.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#containsKey, [], {
              #key: key,
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i17.Future<bool>.value(false),
          )
          as _i17.Future<bool>);

  @override
  _i17.Future<void> delete({
    required String? key,
    _i5.IOSOptions? iOptions,
    _i5.AndroidOptions? aOptions,
    _i5.LinuxOptions? lOptions,
    _i5.WebOptions? webOptions,
    _i5.MacOsOptions? mOptions,
    _i5.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [], {
              #key: key,
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i17.Future<void>.value(),
            returnValueForMissingStub: _i17.Future<void>.value(),
          )
          as _i17.Future<void>);

  @override
  _i17.Future<Map<String, String>> readAll({
    _i5.IOSOptions? iOptions,
    _i5.AndroidOptions? aOptions,
    _i5.LinuxOptions? lOptions,
    _i5.WebOptions? webOptions,
    _i5.MacOsOptions? mOptions,
    _i5.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#readAll, [], {
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i17.Future<Map<String, String>>.value(
              <String, String>{},
            ),
          )
          as _i17.Future<Map<String, String>>);

  @override
  _i17.Future<void> deleteAll({
    _i5.IOSOptions? iOptions,
    _i5.AndroidOptions? aOptions,
    _i5.LinuxOptions? lOptions,
    _i5.WebOptions? webOptions,
    _i5.MacOsOptions? mOptions,
    _i5.WindowsOptions? wOptions,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAll, [], {
              #iOptions: iOptions,
              #aOptions: aOptions,
              #lOptions: lOptions,
              #webOptions: webOptions,
              #mOptions: mOptions,
              #wOptions: wOptions,
            }),
            returnValue: _i17.Future<void>.value(),
            returnValueForMissingStub: _i17.Future<void>.value(),
          )
          as _i17.Future<void>);

  @override
  _i17.Future<bool?> isCupertinoProtectedDataAvailable() =>
      (super.noSuchMethod(
            Invocation.method(#isCupertinoProtectedDataAvailable, []),
            returnValue: _i17.Future<bool?>.value(),
          )
          as _i17.Future<bool?>);
}

/// A class which mocks [JobManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockJobManager extends _i1.Mock implements _i24.JobManager {
  MockJobManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.BehaviorSubject<bool> get isSyncingSubject =>
      (super.noSuchMethod(
            Invocation.getter(#isSyncingSubject),
            returnValue: _FakeBehaviorSubject_11<bool>(
              this,
              Invocation.getter(#isSyncingSubject),
            ),
          )
          as _i6.BehaviorSubject<bool>);

  @override
  _i17.Stream<bool> get isSyncing =>
      (super.noSuchMethod(
            Invocation.getter(#isSyncing),
            returnValue: _i17.Stream<bool>.empty(),
          )
          as _i17.Stream<bool>);

  @override
  _i17.Future<void> sync() =>
      (super.noSuchMethod(
            Invocation.method(#sync, []),
            returnValue: _i17.Future<void>.value(),
            returnValueForMissingStub: _i17.Future<void>.value(),
          )
          as _i17.Future<void>);

  @override
  _i17.Future<void> syncJob(_i8.Job? job) =>
      (super.noSuchMethod(
            Invocation.method(#syncJob, [job]),
            returnValue: _i17.Future<void>.value(),
            returnValueForMissingStub: _i17.Future<void>.value(),
          )
          as _i17.Future<void>);
}

/// A class which mocks [Logger].
///
/// See the documentation for Mockito's code generation for more information.
class MockLogger extends _i1.Mock implements _i25.Logger {
  MockLogger() {
    _i1.throwOnMissingStub(this);
  }

  @override
  void login(_i8.User? user) => super.noSuchMethod(
    Invocation.method(#login, [user]),
    returnValueForMissingStub: null,
  );

  @override
  void logout() => super.noSuchMethod(
    Invocation.method(#logout, []),
    returnValueForMissingStub: null,
  );

  @override
  void setCurrentScreen(String? name) => super.noSuchMethod(
    Invocation.method(#setCurrentScreen, [name]),
    returnValueForMissingStub: null,
  );

  @override
  _i17.Future<dynamic> log(
    String? eventName,
    Map<String, dynamic>? eventParams, {
    bool? isAnonymous = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #log,
              [eventName, eventParams],
              {#isAnonymous: isAnonymous},
            ),
            returnValue: _i17.Future<dynamic>.value(),
          )
          as _i17.Future<dynamic>);

  @override
  void setUserID(String? id) => super.noSuchMethod(
    Invocation.method(#setUserID, [id]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [AppDatabase].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppDatabase extends _i1.Mock implements _i8.AppDatabase {
  @override
  int get schemaVersion =>
      (super.noSuchMethod(
            Invocation.getter(#schemaVersion),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  _i7.MigrationStrategy get migration =>
      (super.noSuchMethod(
            Invocation.getter(#migration),
            returnValue: _FakeMigrationStrategy_12(
              this,
              Invocation.getter(#migration),
            ),
            returnValueForMissingStub: _FakeMigrationStrategy_12(
              this,
              Invocation.getter(#migration),
            ),
          )
          as _i7.MigrationStrategy);

  @override
  List<_i7.TableInfo<_i7.Table, dynamic>> get userRelatedTables =>
      (super.noSuchMethod(
            Invocation.getter(#userRelatedTables),
            returnValue: <_i7.TableInfo<_i7.Table, dynamic>>[],
            returnValueForMissingStub: <_i7.TableInfo<_i7.Table, dynamic>>[],
          )
          as List<_i7.TableInfo<_i7.Table, dynamic>>);

  @override
  _i8.$UsersTable get users =>
      (super.noSuchMethod(
            Invocation.getter(#users),
            returnValue: _Fake$UsersTable_13(this, Invocation.getter(#users)),
            returnValueForMissingStub: _Fake$UsersTable_13(
              this,
              Invocation.getter(#users),
            ),
          )
          as _i8.$UsersTable);

  @override
  _i8.$AuthTokensTable get authTokens =>
      (super.noSuchMethod(
            Invocation.getter(#authTokens),
            returnValue: _Fake$AuthTokensTable_14(
              this,
              Invocation.getter(#authTokens),
            ),
            returnValueForMissingStub: _Fake$AuthTokensTable_14(
              this,
              Invocation.getter(#authTokens),
            ),
          )
          as _i8.$AuthTokensTable);

  @override
  _i8.$NotificationsTable get notifications =>
      (super.noSuchMethod(
            Invocation.getter(#notifications),
            returnValue: _Fake$NotificationsTable_15(
              this,
              Invocation.getter(#notifications),
            ),
            returnValueForMissingStub: _Fake$NotificationsTable_15(
              this,
              Invocation.getter(#notifications),
            ),
          )
          as _i8.$NotificationsTable);

  @override
  _i8.$JobsTable get jobs =>
      (super.noSuchMethod(
            Invocation.getter(#jobs),
            returnValue: _Fake$JobsTable_16(this, Invocation.getter(#jobs)),
            returnValueForMissingStub: _Fake$JobsTable_16(
              this,
              Invocation.getter(#jobs),
            ),
          )
          as _i8.$JobsTable);

  @override
  _i8.$UserListsTable get userLists =>
      (super.noSuchMethod(
            Invocation.getter(#userLists),
            returnValue: _Fake$UserListsTable_17(
              this,
              Invocation.getter(#userLists),
            ),
            returnValueForMissingStub: _Fake$UserListsTable_17(
              this,
              Invocation.getter(#userLists),
            ),
          )
          as _i8.$UserListsTable);

  @override
  _i8.$MovieListsTable get movieLists =>
      (super.noSuchMethod(
            Invocation.getter(#movieLists),
            returnValue: _Fake$MovieListsTable_18(
              this,
              Invocation.getter(#movieLists),
            ),
            returnValueForMissingStub: _Fake$MovieListsTable_18(
              this,
              Invocation.getter(#movieLists),
            ),
          )
          as _i8.$MovieListsTable);

  @override
  _i8.$MovieDescriptionsTable get movieDescriptions =>
      (super.noSuchMethod(
            Invocation.getter(#movieDescriptions),
            returnValue: _Fake$MovieDescriptionsTable_19(
              this,
              Invocation.getter(#movieDescriptions),
            ),
            returnValueForMissingStub: _Fake$MovieDescriptionsTable_19(
              this,
              Invocation.getter(#movieDescriptions),
            ),
          )
          as _i8.$MovieDescriptionsTable);

  @override
  _i9.UserDao get userDao =>
      (super.noSuchMethod(
            Invocation.getter(#userDao),
            returnValue: _FakeUserDao_20(this, Invocation.getter(#userDao)),
            returnValueForMissingStub: _FakeUserDao_20(
              this,
              Invocation.getter(#userDao),
            ),
          )
          as _i9.UserDao);

  @override
  _i10.AuthTokenDao get authTokenDao =>
      (super.noSuchMethod(
            Invocation.getter(#authTokenDao),
            returnValue: _FakeAuthTokenDao_21(
              this,
              Invocation.getter(#authTokenDao),
            ),
            returnValueForMissingStub: _FakeAuthTokenDao_21(
              this,
              Invocation.getter(#authTokenDao),
            ),
          )
          as _i10.AuthTokenDao);

  @override
  _i11.NotificationDao get notificationDao =>
      (super.noSuchMethod(
            Invocation.getter(#notificationDao),
            returnValue: _FakeNotificationDao_22(
              this,
              Invocation.getter(#notificationDao),
            ),
            returnValueForMissingStub: _FakeNotificationDao_22(
              this,
              Invocation.getter(#notificationDao),
            ),
          )
          as _i11.NotificationDao);

  @override
  _i12.JobDao get jobDao =>
      (super.noSuchMethod(
            Invocation.getter(#jobDao),
            returnValue: _FakeJobDao_23(this, Invocation.getter(#jobDao)),
            returnValueForMissingStub: _FakeJobDao_23(
              this,
              Invocation.getter(#jobDao),
            ),
          )
          as _i12.JobDao);

  @override
  _i13.UserListDao get userListDao =>
      (super.noSuchMethod(
            Invocation.getter(#userListDao),
            returnValue: _FakeUserListDao_24(
              this,
              Invocation.getter(#userListDao),
            ),
            returnValueForMissingStub: _FakeUserListDao_24(
              this,
              Invocation.getter(#userListDao),
            ),
          )
          as _i13.UserListDao);

  @override
  _i14.MovieListDao get movieListDao =>
      (super.noSuchMethod(
            Invocation.getter(#movieListDao),
            returnValue: _FakeMovieListDao_25(
              this,
              Invocation.getter(#movieListDao),
            ),
            returnValueForMissingStub: _FakeMovieListDao_25(
              this,
              Invocation.getter(#movieListDao),
            ),
          )
          as _i14.MovieListDao);

  @override
  _i15.MovieDescriptionDao get movieDescriptionDao =>
      (super.noSuchMethod(
            Invocation.getter(#movieDescriptionDao),
            returnValue: _FakeMovieDescriptionDao_26(
              this,
              Invocation.getter(#movieDescriptionDao),
            ),
            returnValueForMissingStub: _FakeMovieDescriptionDao_26(
              this,
              Invocation.getter(#movieDescriptionDao),
            ),
          )
          as _i15.MovieDescriptionDao);

  @override
  _i8.$AppDatabaseManager get managers =>
      (super.noSuchMethod(
            Invocation.getter(#managers),
            returnValue: _Fake$AppDatabaseManager_27(
              this,
              Invocation.getter(#managers),
            ),
            returnValueForMissingStub: _Fake$AppDatabaseManager_27(
              this,
              Invocation.getter(#managers),
            ),
          )
          as _i8.$AppDatabaseManager);

  @override
  Iterable<_i7.TableInfo<_i7.Table, Object?>> get allTables =>
      (super.noSuchMethod(
            Invocation.getter(#allTables),
            returnValue: <_i7.TableInfo<_i7.Table, Object?>>[],
            returnValueForMissingStub: <_i7.TableInfo<_i7.Table, Object?>>[],
          )
          as Iterable<_i7.TableInfo<_i7.Table, Object?>>);

  @override
  List<_i7.DatabaseSchemaEntity> get allSchemaEntities =>
      (super.noSuchMethod(
            Invocation.getter(#allSchemaEntities),
            returnValue: <_i7.DatabaseSchemaEntity>[],
            returnValueForMissingStub: <_i7.DatabaseSchemaEntity>[],
          )
          as List<_i7.DatabaseSchemaEntity>);

  @override
  _i7.GeneratedDatabase get attachedDatabase =>
      (super.noSuchMethod(
            Invocation.getter(#attachedDatabase),
            returnValue: _FakeGeneratedDatabase_28(
              this,
              Invocation.getter(#attachedDatabase),
            ),
            returnValueForMissingStub: _FakeGeneratedDatabase_28(
              this,
              Invocation.getter(#attachedDatabase),
            ),
          )
          as _i7.GeneratedDatabase);

  @override
  _i7.DriftDatabaseOptions get options =>
      (super.noSuchMethod(
            Invocation.getter(#options),
            returnValue: _FakeDriftDatabaseOptions_29(
              this,
              Invocation.getter(#options),
            ),
            returnValueForMissingStub: _FakeDriftDatabaseOptions_29(
              this,
              Invocation.getter(#options),
            ),
          )
          as _i7.DriftDatabaseOptions);

  @override
  _i7.StreamQueryUpdateRules get streamUpdateRules =>
      (super.noSuchMethod(
            Invocation.getter(#streamUpdateRules),
            returnValue: _FakeStreamQueryUpdateRules_30(
              this,
              Invocation.getter(#streamUpdateRules),
            ),
            returnValueForMissingStub: _FakeStreamQueryUpdateRules_30(
              this,
              Invocation.getter(#streamUpdateRules),
            ),
          )
          as _i7.StreamQueryUpdateRules);

  @override
  _i7.DatabaseConnection get connection =>
      (super.noSuchMethod(
            Invocation.getter(#connection),
            returnValue: _FakeDatabaseConnection_31(
              this,
              Invocation.getter(#connection),
            ),
            returnValueForMissingStub: _FakeDatabaseConnection_31(
              this,
              Invocation.getter(#connection),
            ),
          )
          as _i7.DatabaseConnection);

  @override
  _i7.SqlTypes get typeMapping =>
      (super.noSuchMethod(
            Invocation.getter(#typeMapping),
            returnValue: _i19.dummyValue<_i7.SqlTypes>(
              this,
              Invocation.getter(#typeMapping),
            ),
            returnValueForMissingStub: _i19.dummyValue<_i7.SqlTypes>(
              this,
              Invocation.getter(#typeMapping),
            ),
          )
          as _i7.SqlTypes);

  @override
  _i7.QueryExecutor get executor =>
      (super.noSuchMethod(
            Invocation.getter(#executor),
            returnValue: _FakeQueryExecutor_32(
              this,
              Invocation.getter(#executor),
            ),
            returnValueForMissingStub: _FakeQueryExecutor_32(
              this,
              Invocation.getter(#executor),
            ),
          )
          as _i7.QueryExecutor);

  @override
  _i16.StreamQueryStore get streamQueries =>
      (super.noSuchMethod(
            Invocation.getter(#streamQueries),
            returnValue: _FakeStreamQueryStore_33(
              this,
              Invocation.getter(#streamQueries),
            ),
            returnValueForMissingStub: _FakeStreamQueryStore_33(
              this,
              Invocation.getter(#streamQueries),
            ),
          )
          as _i16.StreamQueryStore);

  @override
  _i7.DatabaseConnectionUser get resolvedEngine =>
      (super.noSuchMethod(
            Invocation.getter(#resolvedEngine),
            returnValue: _FakeDatabaseConnectionUser_34(
              this,
              Invocation.getter(#resolvedEngine),
            ),
            returnValueForMissingStub: _FakeDatabaseConnectionUser_34(
              this,
              Invocation.getter(#resolvedEngine),
            ),
          )
          as _i7.DatabaseConnectionUser);

  @override
  _i17.Future<dynamic> deleteAll() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAll, []),
            returnValue: _i17.Future<dynamic>.value(),
            returnValueForMissingStub: _i17.Future<dynamic>.value(),
          )
          as _i17.Future<dynamic>);

  @override
  _i17.Future<dynamic> recreateTables() =>
      (super.noSuchMethod(
            Invocation.method(#recreateTables, []),
            returnValue: _i17.Future<dynamic>.value(),
            returnValueForMissingStub: _i17.Future<dynamic>.value(),
          )
          as _i17.Future<dynamic>);

  @override
  _i17.Future<void> clearUserRelatedTables() =>
      (super.noSuchMethod(
            Invocation.method(#clearUserRelatedTables, []),
            returnValue: _i17.Future<void>.value(),
            returnValueForMissingStub: _i17.Future<void>.value(),
          )
          as _i17.Future<void>);

  @override
  _i7.Migrator createMigrator() =>
      (super.noSuchMethod(
            Invocation.method(#createMigrator, []),
            returnValue: _FakeMigrator_35(
              this,
              Invocation.method(#createMigrator, []),
            ),
            returnValueForMissingStub: _FakeMigrator_35(
              this,
              Invocation.method(#createMigrator, []),
            ),
          )
          as _i7.Migrator);

  @override
  _i17.Future<void> beforeOpen(
    _i7.QueryExecutor? executor,
    _i7.OpeningDetails? details,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#beforeOpen, [executor, details]),
            returnValue: _i17.Future<void>.value(),
            returnValueForMissingStub: _i17.Future<void>.value(),
          )
          as _i17.Future<void>);

  @override
  _i17.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i17.Future<void>.value(),
            returnValueForMissingStub: _i17.Future<void>.value(),
          )
          as _i17.Future<void>);

  @override
  _i17.Stream<T> createStream<T extends Object>(
    _i16.QueryStreamFetcher<T>? stmt,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createStream, [stmt]),
            returnValue: _i17.Stream<T>.empty(),
            returnValueForMissingStub: _i17.Stream<T>.empty(),
          )
          as _i17.Stream<T>);

  @override
  T alias<T, D>(_i7.ResultSetImplementation<T, D>? table, String? alias) =>
      (super.noSuchMethod(
            Invocation.method(#alias, [table, alias]),
            returnValue: _i19.dummyValue<T>(
              this,
              Invocation.method(#alias, [table, alias]),
            ),
            returnValueForMissingStub: _i19.dummyValue<T>(
              this,
              Invocation.method(#alias, [table, alias]),
            ),
          )
          as T);

  @override
  void markTablesUpdated(Iterable<_i7.TableInfo<_i7.Table, dynamic>>? tables) =>
      super.noSuchMethod(
        Invocation.method(#markTablesUpdated, [tables]),
        returnValueForMissingStub: null,
      );

  @override
  void notifyUpdates(Set<_i7.TableUpdate>? updates) => super.noSuchMethod(
    Invocation.method(#notifyUpdates, [updates]),
    returnValueForMissingStub: null,
  );

  @override
  _i17.Stream<Set<_i7.TableUpdate>> tableUpdates([
    _i7.TableUpdateQuery? query = const _i7.TableUpdateQuery.any(),
  ]) =>
      (super.noSuchMethod(
            Invocation.method(#tableUpdates, [query]),
            returnValue: _i17.Stream<Set<_i7.TableUpdate>>.empty(),
            returnValueForMissingStub:
                _i17.Stream<Set<_i7.TableUpdate>>.empty(),
          )
          as _i17.Stream<Set<_i7.TableUpdate>>);

  @override
  _i17.Future<T> doWhenOpened<T>(
    _i17.FutureOr<T> Function(_i7.QueryExecutor)? fn,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#doWhenOpened, [fn]),
            returnValue:
                _i19.ifNotNull(
                  _i19.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#doWhenOpened, [fn]),
                  ),
                  (T v) => _i17.Future<T>.value(v),
                ) ??
                _FakeFuture_36<T>(this, Invocation.method(#doWhenOpened, [fn])),
            returnValueForMissingStub:
                _i19.ifNotNull(
                  _i19.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#doWhenOpened, [fn]),
                  ),
                  (T v) => _i17.Future<T>.value(v),
                ) ??
                _FakeFuture_36<T>(this, Invocation.method(#doWhenOpened, [fn])),
          )
          as _i17.Future<T>);

  @override
  _i7.InsertStatement<T, D> into<T extends _i7.Table, D>(
    _i7.TableInfo<T, D>? table,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#into, [table]),
            returnValue: _FakeInsertStatement_37<T, D>(
              this,
              Invocation.method(#into, [table]),
            ),
            returnValueForMissingStub: _FakeInsertStatement_37<T, D>(
              this,
              Invocation.method(#into, [table]),
            ),
          )
          as _i7.InsertStatement<T, D>);

  @override
  _i7.UpdateStatement<Tbl, R> update<Tbl extends _i7.Table, R>(
    _i7.TableInfo<Tbl, R>? table,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#update, [table]),
            returnValue: _FakeUpdateStatement_38<Tbl, R>(
              this,
              Invocation.method(#update, [table]),
            ),
            returnValueForMissingStub: _FakeUpdateStatement_38<Tbl, R>(
              this,
              Invocation.method(#update, [table]),
            ),
          )
          as _i7.UpdateStatement<Tbl, R>);

  @override
  _i7.SimpleSelectStatement<T, R> select<T extends _i7.HasResultSet, R>(
    _i7.ResultSetImplementation<T, R>? table, {
    bool? distinct = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#select, [table], {#distinct: distinct}),
            returnValue: _FakeSimpleSelectStatement_39<T, R>(
              this,
              Invocation.method(#select, [table], {#distinct: distinct}),
            ),
            returnValueForMissingStub: _FakeSimpleSelectStatement_39<T, R>(
              this,
              Invocation.method(#select, [table], {#distinct: distinct}),
            ),
          )
          as _i7.SimpleSelectStatement<T, R>);

  @override
  _i7.JoinedSelectStatement<T, R> selectOnly<T extends _i7.HasResultSet, R>(
    _i7.ResultSetImplementation<T, R>? table, {
    bool? distinct = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#selectOnly, [table], {#distinct: distinct}),
            returnValue: _FakeJoinedSelectStatement_40<T, R>(
              this,
              Invocation.method(#selectOnly, [table], {#distinct: distinct}),
            ),
            returnValueForMissingStub: _FakeJoinedSelectStatement_40<T, R>(
              this,
              Invocation.method(#selectOnly, [table], {#distinct: distinct}),
            ),
          )
          as _i7.JoinedSelectStatement<T, R>);

  @override
  _i7.BaseSelectStatement<_i7.TypedResult> selectExpressions(
    Iterable<_i7.Expression<Object>>? columns,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#selectExpressions, [columns]),
            returnValue: _FakeBaseSelectStatement_41<_i7.TypedResult>(
              this,
              Invocation.method(#selectExpressions, [columns]),
            ),
            returnValueForMissingStub:
                _FakeBaseSelectStatement_41<_i7.TypedResult>(
                  this,
                  Invocation.method(#selectExpressions, [columns]),
                ),
          )
          as _i7.BaseSelectStatement<_i7.TypedResult>);

  @override
  _i7.DeleteStatement<T, D> delete<T extends _i7.Table, D>(
    _i7.TableInfo<T, D>? table,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [table]),
            returnValue: _FakeDeleteStatement_42<T, D>(
              this,
              Invocation.method(#delete, [table]),
            ),
            returnValueForMissingStub: _FakeDeleteStatement_42<T, D>(
              this,
              Invocation.method(#delete, [table]),
            ),
          )
          as _i7.DeleteStatement<T, D>);

  @override
  _i17.Future<int> customUpdate(
    String? query, {
    List<_i7.Variable<Object>>? variables = const [],
    Set<_i7.ResultSetImplementation<dynamic, dynamic>>? updates,
    _i7.UpdateKind? updateKind,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customUpdate,
              [query],
              {
                #variables: variables,
                #updates: updates,
                #updateKind: updateKind,
              },
            ),
            returnValue: _i17.Future<int>.value(0),
            returnValueForMissingStub: _i17.Future<int>.value(0),
          )
          as _i17.Future<int>);

  @override
  _i17.Future<int> customInsert(
    String? query, {
    List<_i7.Variable<Object>>? variables = const [],
    Set<_i7.ResultSetImplementation<dynamic, dynamic>>? updates,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customInsert,
              [query],
              {#variables: variables, #updates: updates},
            ),
            returnValue: _i17.Future<int>.value(0),
            returnValueForMissingStub: _i17.Future<int>.value(0),
          )
          as _i17.Future<int>);

  @override
  _i17.Future<List<_i7.QueryRow>> customWriteReturning(
    String? query, {
    List<_i7.Variable<Object>>? variables = const [],
    Set<_i7.ResultSetImplementation<dynamic, dynamic>>? updates,
    _i7.UpdateKind? updateKind,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customWriteReturning,
              [query],
              {
                #variables: variables,
                #updates: updates,
                #updateKind: updateKind,
              },
            ),
            returnValue: _i17.Future<List<_i7.QueryRow>>.value(
              <_i7.QueryRow>[],
            ),
            returnValueForMissingStub: _i17.Future<List<_i7.QueryRow>>.value(
              <_i7.QueryRow>[],
            ),
          )
          as _i17.Future<List<_i7.QueryRow>>);

  @override
  _i7.Selectable<_i7.QueryRow> customSelect(
    String? query, {
    List<_i7.Variable<Object>>? variables = const [],
    Set<_i7.ResultSetImplementation<dynamic, dynamic>>? readsFrom = const {},
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customSelect,
              [query],
              {#variables: variables, #readsFrom: readsFrom},
            ),
            returnValue: _FakeSelectable_43<_i7.QueryRow>(
              this,
              Invocation.method(
                #customSelect,
                [query],
                {#variables: variables, #readsFrom: readsFrom},
              ),
            ),
            returnValueForMissingStub: _FakeSelectable_43<_i7.QueryRow>(
              this,
              Invocation.method(
                #customSelect,
                [query],
                {#variables: variables, #readsFrom: readsFrom},
              ),
            ),
          )
          as _i7.Selectable<_i7.QueryRow>);

  @override
  _i7.Selectable<_i7.QueryRow> customSelectQuery(
    String? query, {
    List<_i7.Variable<Object>>? variables = const [],
    Set<_i7.ResultSetImplementation<dynamic, dynamic>>? readsFrom = const {},
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #customSelectQuery,
              [query],
              {#variables: variables, #readsFrom: readsFrom},
            ),
            returnValue: _FakeSelectable_43<_i7.QueryRow>(
              this,
              Invocation.method(
                #customSelectQuery,
                [query],
                {#variables: variables, #readsFrom: readsFrom},
              ),
            ),
            returnValueForMissingStub: _FakeSelectable_43<_i7.QueryRow>(
              this,
              Invocation.method(
                #customSelectQuery,
                [query],
                {#variables: variables, #readsFrom: readsFrom},
              ),
            ),
          )
          as _i7.Selectable<_i7.QueryRow>);

  @override
  _i17.Future<void> customStatement(String? statement, [List<dynamic>? args]) =>
      (super.noSuchMethod(
            Invocation.method(#customStatement, [statement, args]),
            returnValue: _i17.Future<void>.value(),
            returnValueForMissingStub: _i17.Future<void>.value(),
          )
          as _i17.Future<void>);

  @override
  _i17.Future<T> transaction<T>(
    _i17.Future<T> Function()? action, {
    bool? requireNew = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #transaction,
              [action],
              {#requireNew: requireNew},
            ),
            returnValue:
                _i19.ifNotNull(
                  _i19.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #transaction,
                      [action],
                      {#requireNew: requireNew},
                    ),
                  ),
                  (T v) => _i17.Future<T>.value(v),
                ) ??
                _FakeFuture_36<T>(
                  this,
                  Invocation.method(
                    #transaction,
                    [action],
                    {#requireNew: requireNew},
                  ),
                ),
            returnValueForMissingStub:
                _i19.ifNotNull(
                  _i19.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #transaction,
                      [action],
                      {#requireNew: requireNew},
                    ),
                  ),
                  (T v) => _i17.Future<T>.value(v),
                ) ??
                _FakeFuture_36<T>(
                  this,
                  Invocation.method(
                    #transaction,
                    [action],
                    {#requireNew: requireNew},
                  ),
                ),
          )
          as _i17.Future<T>);

  @override
  _i17.Future<T> exclusively<T>(_i17.Future<T> Function()? action) =>
      (super.noSuchMethod(
            Invocation.method(#exclusively, [action]),
            returnValue:
                _i19.ifNotNull(
                  _i19.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#exclusively, [action]),
                  ),
                  (T v) => _i17.Future<T>.value(v),
                ) ??
                _FakeFuture_36<T>(
                  this,
                  Invocation.method(#exclusively, [action]),
                ),
            returnValueForMissingStub:
                _i19.ifNotNull(
                  _i19.dummyValueOrNull<T>(
                    this,
                    Invocation.method(#exclusively, [action]),
                  ),
                  (T v) => _i17.Future<T>.value(v),
                ) ??
                _FakeFuture_36<T>(
                  this,
                  Invocation.method(#exclusively, [action]),
                ),
          )
          as _i17.Future<T>);

  @override
  _i17.Future<void> batch(
    _i17.FutureOr<void> Function(_i7.Batch)? runInBatch,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#batch, [runInBatch]),
            returnValue: _i17.Future<void>.value(),
            returnValueForMissingStub: _i17.Future<void>.value(),
          )
          as _i17.Future<void>);

  @override
  _i17.Future<T> runWithInterceptor<T>(
    _i17.Future<T> Function()? action, {
    required _i7.QueryInterceptor? interceptor,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #runWithInterceptor,
              [action],
              {#interceptor: interceptor},
            ),
            returnValue:
                _i19.ifNotNull(
                  _i19.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #runWithInterceptor,
                      [action],
                      {#interceptor: interceptor},
                    ),
                  ),
                  (T v) => _i17.Future<T>.value(v),
                ) ??
                _FakeFuture_36<T>(
                  this,
                  Invocation.method(
                    #runWithInterceptor,
                    [action],
                    {#interceptor: interceptor},
                  ),
                ),
            returnValueForMissingStub:
                _i19.ifNotNull(
                  _i19.dummyValueOrNull<T>(
                    this,
                    Invocation.method(
                      #runWithInterceptor,
                      [action],
                      {#interceptor: interceptor},
                    ),
                  ),
                  (T v) => _i17.Future<T>.value(v),
                ) ??
                _FakeFuture_36<T>(
                  this,
                  Invocation.method(
                    #runWithInterceptor,
                    [action],
                    {#interceptor: interceptor},
                  ),
                ),
          )
          as _i17.Future<T>);

  @override
  _i7.GenerationContext $write(
    _i7.Component? component, {
    bool? hasMultipleTables,
    int? startIndex,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #$write,
              [component],
              {#hasMultipleTables: hasMultipleTables, #startIndex: startIndex},
            ),
            returnValue: _FakeGenerationContext_44(
              this,
              Invocation.method(
                #$write,
                [component],
                {
                  #hasMultipleTables: hasMultipleTables,
                  #startIndex: startIndex,
                },
              ),
            ),
            returnValueForMissingStub: _FakeGenerationContext_44(
              this,
              Invocation.method(
                #$write,
                [component],
                {
                  #hasMultipleTables: hasMultipleTables,
                  #startIndex: startIndex,
                },
              ),
            ),
          )
          as _i7.GenerationContext);

  @override
  _i7.GenerationContext $writeInsertable(
    _i7.TableInfo<_i7.Table, dynamic>? table,
    _i7.Insertable<dynamic>? insertable, {
    int? startIndex,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #$writeInsertable,
              [table, insertable],
              {#startIndex: startIndex},
            ),
            returnValue: _FakeGenerationContext_44(
              this,
              Invocation.method(
                #$writeInsertable,
                [table, insertable],
                {#startIndex: startIndex},
              ),
            ),
            returnValueForMissingStub: _FakeGenerationContext_44(
              this,
              Invocation.method(
                #$writeInsertable,
                [table, insertable],
                {#startIndex: startIndex},
              ),
            ),
          )
          as _i7.GenerationContext);

  @override
  String $expandVar(int? start, int? amount) =>
      (super.noSuchMethod(
            Invocation.method(#$expandVar, [start, amount]),
            returnValue: _i19.dummyValue<String>(
              this,
              Invocation.method(#$expandVar, [start, amount]),
            ),
            returnValueForMissingStub: _i19.dummyValue<String>(
              this,
              Invocation.method(#$expandVar, [start, amount]),
            ),
          )
          as String);
}

/// A class which mocks [Selectable].
///
/// See the documentation for Mockito's code generation for more information.
class MockCustomSelectOfInt extends _i1.Mock implements _i7.Selectable<int> {
  @override
  _i17.Future<List<int>> get() =>
      (super.noSuchMethod(
            Invocation.method(#get, []),
            returnValue: _i17.Future<List<int>>.value(<int>[]),
            returnValueForMissingStub: _i17.Future<List<int>>.value(<int>[]),
          )
          as _i17.Future<List<int>>);

  @override
  _i17.Stream<List<int>> watch() =>
      (super.noSuchMethod(
            Invocation.method(#watch, []),
            returnValue: _i17.Stream<List<int>>.empty(),
            returnValueForMissingStub: _i17.Stream<List<int>>.empty(),
          )
          as _i17.Stream<List<int>>);

  @override
  _i17.Future<int> getSingle() =>
      (super.noSuchMethod(
            Invocation.method(#getSingle, []),
            returnValue: _i17.Future<int>.value(0),
            returnValueForMissingStub: _i17.Future<int>.value(0),
          )
          as _i17.Future<int>);

  @override
  _i17.Stream<int> watchSingle() =>
      (super.noSuchMethod(
            Invocation.method(#watchSingle, []),
            returnValue: _i17.Stream<int>.empty(),
            returnValueForMissingStub: _i17.Stream<int>.empty(),
          )
          as _i17.Stream<int>);

  @override
  _i17.Future<int?> getSingleOrNull() =>
      (super.noSuchMethod(
            Invocation.method(#getSingleOrNull, []),
            returnValue: _i17.Future<int?>.value(),
            returnValueForMissingStub: _i17.Future<int?>.value(),
          )
          as _i17.Future<int?>);

  @override
  _i17.Stream<int?> watchSingleOrNull() =>
      (super.noSuchMethod(
            Invocation.method(#watchSingleOrNull, []),
            returnValue: _i17.Stream<int?>.empty(),
            returnValueForMissingStub: _i17.Stream<int?>.empty(),
          )
          as _i17.Stream<int?>);

  @override
  _i7.Selectable<N> map<N>(N Function(int)? mapper) =>
      (super.noSuchMethod(
            Invocation.method(#map, [mapper]),
            returnValue: _FakeSelectable_43<N>(
              this,
              Invocation.method(#map, [mapper]),
            ),
            returnValueForMissingStub: _FakeSelectable_43<N>(
              this,
              Invocation.method(#map, [mapper]),
            ),
          )
          as _i7.Selectable<N>);

  @override
  _i7.Selectable<N> asyncMap<N>(_i17.FutureOr<N> Function(int)? mapper) =>
      (super.noSuchMethod(
            Invocation.method(#asyncMap, [mapper]),
            returnValue: _FakeSelectable_43<N>(
              this,
              Invocation.method(#asyncMap, [mapper]),
            ),
            returnValueForMissingStub: _FakeSelectable_43<N>(
              this,
              Invocation.method(#asyncMap, [mapper]),
            ),
          )
          as _i7.Selectable<N>);
}
