// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show TargetPlatform, defaultTargetPlatform, kIsWeb;
import 'package:platform_common/config.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return _getWebOption(Config.appFlavor);
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return _getMacOSOption(Config.appFlavor);
      case TargetPlatform.windows:
        return _getWebOption(Config.appFlavor);
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static FirebaseOptions _getWebOption(Flavor flavor) {
    return switch (flavor.name) {
      FlavorName.production => const FirebaseOptions(
          apiKey: "AIzaSyDOQgdejxUT0VdkWnISpjfshED-vPEyYZA",
          appId: "1:706671687188:web:bdb053aa550df9734e1901",
          authDomain: "thinkpalm-maridock.firebaseapp.com",
          measurementId: "G-RTVMVX4LZG",
          messagingSenderId: "706671687188",
          projectId: "thinkpalm-maridock",
          storageBucket: "thinkpalm-maridock.firebasestorage.app",
        ),
      FlavorName.staging => const FirebaseOptions(
          apiKey: "AIzaSyDOQgdejxUT0VdkWnISpjfshED-vPEyYZA",
          appId: "1:706671687188:web:0e24ec41294b15e54e1901",
          authDomain: "thinkpalm-maridock.firebaseapp.com",
          measurementId: "G-E5060WGY22",
          messagingSenderId: "706671687188",
          projectId: "thinkpalm-maridock",
          storageBucket: "thinkpalm-maridock.firebasestorage.app",
        ),
      FlavorName.qa => const FirebaseOptions(
          apiKey: "AIzaSyDOQgdejxUT0VdkWnISpjfshED-vPEyYZA",
          appId: "1:706671687188:web:3f07ac81d8e9c2954e1901",
          authDomain: "thinkpalm-maridock.firebaseapp.com",
          measurementId: "G-ZETE11V85F",
          messagingSenderId: "706671687188",
          projectId: "thinkpalm-maridock",
          storageBucket: "thinkpalm-maridock.firebasestorage.app",
        ),
      _ => const FirebaseOptions(
          apiKey: "AIzaSyDOQgdejxUT0VdkWnISpjfshED-vPEyYZA",
          appId: "1:706671687188:web:da49216d0582aa274e1901",
          authDomain: "thinkpalm-maridock.firebaseapp.com",
          measurementId: "G-GZSZDFMXN7",
          messagingSenderId: "706671687188",
          projectId: "thinkpalm-maridock",
          storageBucket: "thinkpalm-maridock.firebasestorage.app",
        )
    };
  }

  static FirebaseOptions _getMacOSOption(Flavor flavor) {
    return switch (flavor.name) {
      FlavorName.production => const FirebaseOptions(
          apiKey: "AIzaSyCzhG12CaPMUJG2kOLDYzN4tXYq1oR1HDw",
          appId: "1:706671687188:ios:3516866266b65e0b4e1901",
          authDomain: "thinkpalm-maridock.firebaseapp.com",
          databaseURL: "https://thinkpalm-maridock.firebaseio.com",
          iosBundleId: 'com.platform.common',
          measurementId: "G-RTVMVX4LZG",
          messagingSenderId: "706671687188",
          projectId: "thinkpalm-maridock",
          storageBucket: "thinkpalm-maridock.firebasestorage.app",
        ),
      FlavorName.staging => const FirebaseOptions(
          apiKey: "AIzaSyCzhG12CaPMUJG2kOLDYzN4tXYq1oR1HDw",
          appId: "1:706671687188:ios:6a52106ee25fcd5e4e1901",
          authDomain: "thinkpalm-maridock.firebaseapp.com",
          databaseURL: "https://thinkpalm-maridock.firebaseio.com",
          iosBundleId: 'com.platform.common.stage',
          measurementId: "G-E5060WGY22",
          messagingSenderId: "706671687188",
          projectId: "thinkpalm-maridock",
          storageBucket: "thinkpalm-maridock.firebasestorage.app",
        ),
      FlavorName.qa => const FirebaseOptions(
          apiKey: "AIzaSyCzhG12CaPMUJG2kOLDYzN4tXYq1oR1HDw",
          appId: "1:706671687188:ios:8e73d67ce5dd1b254e1901",
          authDomain: "thinkpalm-maridock.firebaseapp.com",
          databaseURL: "https://thinkpalm-maridock.firebaseio.com",
          iosBundleId: 'com.platform.common.qa',
          measurementId: "G-ZETE11V85F",
          messagingSenderId: "706671687188",
          projectId: "thinkpalm-maridock",
          storageBucket: "thinkpalm-maridock.firebasestorage.app",
        ),
      _ => const FirebaseOptions(
          apiKey: 'AIzaSyCzhG12CaPMUJG2kOLDYzN4tXYq1oR1HDw',
          appId: '1:706671687188:ios:57d57648244c9ad54e1901',
          authDomain: "thinkpalm-maridock.firebaseapp.com",
          databaseURL: "https://thinkpalm-maridock.firebaseio.com",
          iosBundleId: 'com.platform.common.dev',
          measurementId: "G-GZSZDFMXN7",
          messagingSenderId: "706671687188",
          projectId: "thinkpalm-maridock",
          storageBucket: "thinkpalm-maridock.firebasestorage.app",
        )
    };
  }
}
